<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div style="display: flex; align-items: center; background-color: black; color: white; padding: 15px;">
    <img src="<?= $block->getViewFileUrl('DevAll_TableRates::images/logo.png'); ?>" alt="developers-alliance.com" style="margin-right: 15px; width: auto; height: 80px;">
    <div>
        <p style="margin: 0; font-size: 16px; padding-bottom: 5px;">
            The Table Rates module is proudly developed by Developers-Alliance. For assistance, reach out to us:
        </p>
        <p style="margin: 0; font-size: 14px;">
            <a href="https://developers-alliance.com" style="color: white; text-decoration: underline;">developers-alliance.com</a> or email us at
            <a href="mailto:hello@developers-alliance.com" style="color: white; text-decoration: underline;">hello@developers-alliance.com</a>
        </p>
    </div>
</div>
